root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
  project: ["./tsconfig.base.json", "./packages/**/tsconfig.json"]
plugins:
  ["@typescript-eslint"]
extends: [
  "eslint:recommended",
  "plugin:@typescript-eslint/recommended",
  "plugin:prettier/recommended"
]
overrides:
- extends:
  - "plugin:react-hooks/recommended"
  files:
  - "packages/core/**/*.ts?(x)"
  - "packages/core/**/*.js?(x)"
  plugins:
  - "react-refresh"
  rules:
    'react-refresh/only-export-components': warn